-- MVP San Francisco nightlife venue seed data (best-effort real venues + approximate coordinates)
-- Source file: data/venues/sf_seed.csv
--
-- ID note: each row receives a UUID primary key from gen_random_uuid().
-- The mock/in-memory layer uses slug-style IDs (e.g. "venue-audio"); those are stored
-- in metadata->>'seed_id' to bridge mock IDs to DB UUIDs during future migration.

INSERT INTO venues (slug, name, city, state, country_code, latitude, longitude, source, metadata)
VALUES
  ('audio', 'Audio', 'San Francisco', 'CA', 'US', 37.780591, -122.41405, 'seed:mvp', '{"seed_id": "venue-audio", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('halcyon', 'Halcyon', 'San Francisco', 'CA', 'US', 37.775125, -122.410482, 'seed:mvp', '{"seed_id": "venue-halcyon", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('1015-folsom', '1015 Folsom', 'San Francisco', 'CA', 'US', 37.782047, -122.402319, 'seed:mvp', '{"seed_id": "venue-1015-folsom", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('temple-nightclub', 'Temple Nightclub', 'San Francisco', 'CA', 'US', 37.784383, -122.412935, 'seed:mvp', '{"seed_id": "venue-temple-nightclub", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('monarch', 'Monarch', 'San Francisco', 'CA', 'US', 37.777329, -122.413964, 'seed:mvp', '{"seed_id": "venue-monarch", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('butter-sf', 'Butter SF', 'San Francisco', 'CA', 'US', 37.77428, -122.405404, 'seed:mvp', '{"seed_id": "venue-butter-sf", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('public-works', 'Public Works', 'San Francisco', 'CA', 'US', 37.771398, -122.410921, 'seed:mvp', '{"seed_id": "venue-public-works", "neighborhood": "SoMa", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('great-northern', 'Great Northern', 'San Francisco', 'CA', 'US', 37.780748, -122.404691, 'seed:mvp', '{"seed_id": "venue-great-northern", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('dna-lounge', 'DNA Lounge', 'San Francisco', 'CA', 'US', 37.774307, -122.403893, 'seed:mvp', '{"seed_id": "venue-dna-lounge", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-endup', 'The EndUp', 'San Francisco', 'CA', 'US', 37.783141, -122.414383, 'seed:mvp', '{"seed_id": "venue-the-endup", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('raven-bar', 'Raven Bar', 'San Francisco', 'CA', 'US', 37.783087, -122.401933, 'seed:mvp', '{"seed_id": "venue-raven-bar", "neighborhood": "SoMa", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('district-san-francisco', 'District San Francisco', 'San Francisco', 'CA', 'US', 37.776104, -122.411701, 'seed:mvp', '{"seed_id": "venue-district-san-francisco", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('oasis-arts-soma-pop-up', 'Oasis Arts (SoMa Pop-up)', 'San Francisco', 'CA', 'US', 37.785358, -122.408441, 'seed:mvp', '{"seed_id": "venue-oasis-arts-soma-pop-up", "neighborhood": "SoMa", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('cat-club', 'Cat Club', 'San Francisco', 'CA', 'US', 37.772391, -122.412759, 'seed:mvp', '{"seed_id": "venue-cat-club", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('f8-1192', 'F8 1192', 'San Francisco', 'CA', 'US', 37.783712, -122.403633, 'seed:mvp', '{"seed_id": "venue-f8-1192", "neighborhood": "SoMa", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('el-rio', 'El Rio', 'San Francisco', 'CA', 'US', 37.764107, -122.410665, 'seed:mvp', '{"seed_id": "venue-el-rio", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('make-out-room', 'Make-Out Room', 'San Francisco', 'CA', 'US', 37.760043, -122.406284, 'seed:mvp', '{"seed_id": "venue-make-out-room", "neighborhood": "Mission", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-chapel', 'The Chapel', 'San Francisco', 'CA', 'US', 37.757678, -122.413863, 'seed:mvp', '{"seed_id": "venue-the-chapel", "neighborhood": "Mission", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('valencia-room', 'Valencia Room', 'San Francisco', 'CA', 'US', 37.764441, -122.412667, 'seed:mvp', '{"seed_id": "venue-valencia-room", "neighborhood": "Mission", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('blondie-s-bar', 'Blondie''s Bar', 'San Francisco', 'CA', 'US', 37.764926, -122.413408, 'seed:mvp', '{"seed_id": "venue-blondie-s-bar", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-beehive-sf', 'The Beehive SF', 'San Francisco', 'CA', 'US', 37.762569, -122.422975, 'seed:mvp', '{"seed_id": "venue-the-beehive-sf", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('abv', 'ABV', 'San Francisco', 'CA', 'US', 37.755418, -122.418591, 'seed:mvp', '{"seed_id": "venue-abv", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('trick-dog', 'Trick Dog', 'San Francisco', 'CA', 'US', 37.753197, -122.41961, 'seed:mvp', '{"seed_id": "venue-trick-dog", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('lolinda-bar', 'Lolinda Bar', 'San Francisco', 'CA', 'US', 37.753515, -122.418796, 'seed:mvp', '{"seed_id": "venue-lolinda-bar", "neighborhood": "Mission", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('dr-teeth-and-the-electric-mayhem', 'Dr. Teeth and the Electric Mayhem', 'San Francisco', 'CA', 'US', 37.761535, -122.417233, 'seed:mvp', '{"seed_id": "venue-dr-teeth-and-the-electric-mayhem", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('latin-american-club', 'Latin American Club', 'San Francisco', 'CA', 'US', 37.757553, -122.420029, 'seed:mvp', '{"seed_id": "venue-latin-american-club", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('shotwell-s', 'Shotwell''s', 'San Francisco', 'CA', 'US', 37.756005, -122.40694, 'seed:mvp', '{"seed_id": "venue-shotwell-s", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('bender-s-bar-grill', 'Bender''s Bar & Grill', 'San Francisco', 'CA', 'US', 37.761721, -122.412836, 'seed:mvp', '{"seed_id": "venue-bender-s-bar-grill", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('zeitgeist', 'Zeitgeist', 'San Francisco', 'CA', 'US', 37.754567, -122.410676, 'seed:mvp', '{"seed_id": "venue-zeitgeist", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('kilowatt', 'Kilowatt', 'San Francisco', 'CA', 'US', 37.754451, -122.41697, 'seed:mvp', '{"seed_id": "venue-kilowatt", "neighborhood": "Mission", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-cafe', 'The Cafe', 'San Francisco', 'CA', 'US', 37.768243, -122.43248, 'seed:mvp', '{"seed_id": "venue-the-cafe", "neighborhood": "Castro", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('beaux', 'Beaux', 'San Francisco', 'CA', 'US', 37.761754, -122.431677, 'seed:mvp', '{"seed_id": "venue-beaux", "neighborhood": "Castro", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('twin-peaks-tavern', 'Twin Peaks Tavern', 'San Francisco', 'CA', 'US', 37.766043, -122.430032, 'seed:mvp', '{"seed_id": "venue-twin-peaks-tavern", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('440-castro', '440 Castro', 'San Francisco', 'CA', 'US', 37.756836, -122.443422, 'seed:mvp', '{"seed_id": "venue-440-castro", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('moby-dick', 'Moby Dick', 'San Francisco', 'CA', 'US', 37.758132, -122.439181, 'seed:mvp', '{"seed_id": "venue-moby-dick", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('toad-hall', 'Toad Hall', 'San Francisco', 'CA', 'US', 37.756565, -122.427028, 'seed:mvp', '{"seed_id": "venue-toad-hall", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('last-call', 'Last Call', 'San Francisco', 'CA', 'US', 37.766546, -122.438336, 'seed:mvp', '{"seed_id": "venue-last-call", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('badlands', 'Badlands', 'San Francisco', 'CA', 'US', 37.763232, -122.436879, 'seed:mvp', '{"seed_id": "venue-badlands", "neighborhood": "Castro", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-mix', 'The Mix', 'San Francisco', 'CA', 'US', 37.767118, -122.435741, 'seed:mvp', '{"seed_id": "venue-the-mix", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('hi-tops', 'Hi Tops', 'San Francisco', 'CA', 'US', 37.757373, -122.439561, 'seed:mvp', '{"seed_id": "venue-hi-tops", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('lookout', 'Lookout', 'San Francisco', 'CA', 'US', 37.761821, -122.439271, 'seed:mvp', '{"seed_id": "venue-lookout", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('midnight-sun', 'Midnight Sun', 'San Francisco', 'CA', 'US', 37.762169, -122.427839, 'seed:mvp', '{"seed_id": "venue-midnight-sun", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-edge', 'The Edge', 'San Francisco', 'CA', 'US', 37.759391, -122.440052, 'seed:mvp', '{"seed_id": "venue-the-edge", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('pilsner-inn', 'Pilsner Inn', 'San Francisco', 'CA', 'US', 37.768363, -122.434829, 'seed:mvp', '{"seed_id": "venue-pilsner-inn", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('harvey-s', 'Harvey''s', 'San Francisco', 'CA', 'US', 37.754764, -122.443152, 'seed:mvp', '{"seed_id": "venue-harvey-s", "neighborhood": "Castro", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-saloon', 'The Saloon', 'San Francisco', 'CA', 'US', 37.795945, -122.406806, 'seed:mvp', '{"seed_id": "venue-the-saloon", "neighborhood": "North Beach", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('comstock-saloon', 'Comstock Saloon', 'San Francisco', 'CA', 'US', 37.806181, -122.410501, 'seed:mvp', '{"seed_id": "venue-comstock-saloon", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('tony-nik-s-cafe', 'Tony Nik''s Cafe', 'San Francisco', 'CA', 'US', 37.795253, -122.411231, 'seed:mvp', '{"seed_id": "venue-tony-nik-s-cafe", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('15-romolo', '15 Romolo', 'San Francisco', 'CA', 'US', 37.809242, -122.408576, 'seed:mvp', '{"seed_id": "venue-15-romolo", "neighborhood": "North Beach", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('bodega-north-beach', 'Bodega North Beach', 'San Francisco', 'CA', 'US', 37.808866, -122.402606, 'seed:mvp', '{"seed_id": "venue-bodega-north-beach", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('specs-twelve-adler-museum-cafe', 'Specs'' Twelve Adler Museum Cafe', 'San Francisco', 'CA', 'US', 37.794472, -122.405127, 'seed:mvp', '{"seed_id": "venue-specs-twelve-adler-museum-cafe", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('maggie-mcgarry-s', 'Maggie McGarry''s', 'San Francisco', 'CA', 'US', 37.804526, -122.408435, 'seed:mvp', '{"seed_id": "venue-maggie-mcgarry-s", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-boardroom', 'The Boardroom', 'San Francisco', 'CA', 'US', 37.798302, -122.406563, 'seed:mvp', '{"seed_id": "venue-the-boardroom", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('savoy-tivoli', 'Savoy Tivoli', 'San Francisco', 'CA', 'US', 37.795973, -122.410274, 'seed:mvp', '{"seed_id": "venue-savoy-tivoli", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('belle-cora', 'Belle Cora', 'San Francisco', 'CA', 'US', 37.801106, -122.400931, 'seed:mvp', '{"seed_id": "venue-belle-cora", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('vesuvio-cafe', 'Vesuvio Cafe', 'San Francisco', 'CA', 'US', 37.807438, -122.413359, 'seed:mvp', '{"seed_id": "venue-vesuvio-cafe", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('tupelo', 'Tupelo', 'San Francisco', 'CA', 'US', 37.801809, -122.414884, 'seed:mvp', '{"seed_id": "venue-tupelo", "neighborhood": "North Beach", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('gino-carlo', 'Gino & Carlo', 'San Francisco', 'CA', 'US', 37.807989, -122.402431, 'seed:mvp', '{"seed_id": "venue-gino-carlo", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('li-po-lounge', 'Li Po Lounge', 'San Francisco', 'CA', 'US', 37.798777, -122.406599, 'seed:mvp', '{"seed_id": "venue-li-po-lounge", "neighborhood": "North Beach", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('columbus-cafe', 'Columbus Cafe', 'San Francisco', 'CA', 'US', 37.803435, -122.415349, 'seed:mvp', '{"seed_id": "venue-columbus-cafe", "neighborhood": "North Beach", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('balboa-cafe', 'Balboa Cafe', 'San Francisco', 'CA', 'US', 37.805138, -122.436891, 'seed:mvp', '{"seed_id": "venue-balboa-cafe", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('white-rabbit', 'White Rabbit', 'San Francisco', 'CA', 'US', 37.805379, -122.437054, 'seed:mvp', '{"seed_id": "venue-white-rabbit", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('westwood', 'Westwood', 'San Francisco', 'CA', 'US', 37.793709, -122.440765, 'seed:mvp', '{"seed_id": "venue-westwood", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-tipsy-pig', 'The Tipsy Pig', 'San Francisco', 'CA', 'US', 37.793992, -122.429876, 'seed:mvp', '{"seed_id": "venue-the-tipsy-pig", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('palm-house', 'Palm House', 'San Francisco', 'CA', 'US', 37.806881, -122.43163, 'seed:mvp', '{"seed_id": "venue-palm-house", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('monaghan-s', 'Monaghan''s', 'San Francisco', 'CA', 'US', 37.798313, -122.445557, 'seed:mvp', '{"seed_id": "venue-monaghan-s", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-dorian', 'The Dorian', 'San Francisco', 'CA', 'US', 37.80687, -122.429555, 'seed:mvp', '{"seed_id": "venue-the-dorian", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('reed-greenough', 'Reed & Greenough', 'San Francisco', 'CA', 'US', 37.794985, -122.437852, 'seed:mvp', '{"seed_id": "venue-reed-greenough", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('silver-cloud', 'Silver Cloud', 'San Francisco', 'CA', 'US', 37.794738, -122.432909, 'seed:mvp', '{"seed_id": "venue-silver-cloud", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-blue-light', 'The Blue Light', 'San Francisco', 'CA', 'US', 37.805188, -122.444289, 'seed:mvp', '{"seed_id": "venue-the-blue-light", "neighborhood": "Marina", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-brixton', 'The Brixton', 'San Francisco', 'CA', 'US', 37.800829, -122.436704, 'seed:mvp', '{"seed_id": "venue-the-brixton", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('campus-sf', 'Campus SF', 'San Francisco', 'CA', 'US', 37.797676, -122.430896, 'seed:mvp', '{"seed_id": "venue-campus-sf", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('del-mar', 'Del Mar', 'San Francisco', 'CA', 'US', 37.800047, -122.442788, 'seed:mvp', '{"seed_id": "venue-del-mar", "neighborhood": "Marina", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('lush-lounge', 'Lush Lounge', 'San Francisco', 'CA', 'US', 37.801789, -122.433461, 'seed:mvp', '{"seed_id": "venue-lush-lounge", "neighborhood": "Marina", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('the-patio', 'The Patio', 'San Francisco', 'CA', 'US', 37.796717, -122.440989, 'seed:mvp', '{"seed_id": "venue-the-patio", "neighborhood": "Marina", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('kozy-kar', 'Kozy Kar', 'San Francisco', 'CA', 'US', 37.797327, -122.418302, 'seed:mvp', '{"seed_id": "venue-kozy-kar", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('mayes-oyster-house', 'Mayes Oyster House', 'San Francisco', 'CA', 'US', 37.788972, -122.420684, 'seed:mvp', '{"seed_id": "venue-mayes-oyster-house", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('mcteague-s-saloon', 'McTeague''s Saloon', 'San Francisco', 'CA', 'US', 37.784215, -122.425955, 'seed:mvp', '{"seed_id": "venue-mcteague-s-saloon", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('hemlock-tavern-annex', 'Hemlock Tavern Annex', 'San Francisco', 'CA', 'US', 37.787471, -122.41941, 'seed:mvp', '{"seed_id": "venue-hemlock-tavern-annex", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('harper-rye', 'Harper & Rye', 'San Francisco', 'CA', 'US', 37.785852, -122.426036, 'seed:mvp', '{"seed_id": "venue-harper-rye", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('route-101', 'Route 101', 'San Francisco', 'CA', 'US', 37.783465, -122.41864, 'seed:mvp', '{"seed_id": "venue-route-101", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('polkcha', 'Polkcha', 'San Francisco', 'CA', 'US', 37.785834, -122.413702, 'seed:mvp', '{"seed_id": "venue-polkcha", "neighborhood": "Lower Nob Hill/Polk", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('hi-lo-club', 'Hi-Lo Club', 'San Francisco', 'CA', 'US', 37.795295, -122.428725, 'seed:mvp', '{"seed_id": "venue-hi-lo-club", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('decodance-bar', 'Decodance Bar', 'San Francisco', 'CA', 'US', 37.78597, -122.417958, 'seed:mvp', '{"seed_id": "venue-decodance-bar", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('r-bar', 'R Bar', 'San Francisco', 'CA', 'US', 37.785614, -122.427618, 'seed:mvp', '{"seed_id": "venue-r-bar", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('nite-cap', 'Nite Cap', 'San Francisco', 'CA', 'US', 37.796433, -122.419721, 'seed:mvp', '{"seed_id": "venue-nite-cap", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('jackalope', 'Jackalope', 'San Francisco', 'CA', 'US', 37.78949, -122.415877, 'seed:mvp', '{"seed_id": "venue-jackalope", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('rouge-nightclub', 'Rouge Nightclub', 'San Francisco', 'CA', 'US', 37.794512, -122.426573, 'seed:mvp', '{"seed_id": "venue-rouge-nightclub", "neighborhood": "Lower Nob Hill/Polk", "category": "club", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('peacekeeper', 'Peacekeeper', 'San Francisco', 'CA', 'US', 37.783854, -122.422241, 'seed:mvp', '{"seed_id": "venue-peacekeeper", "neighborhood": "Lower Nob Hill/Polk", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('stookey-s-club-moderne', 'Stookey''s Club Moderne', 'San Francisco', 'CA', 'US', 37.788754, -122.421594, 'seed:mvp', '{"seed_id": "venue-stookey-s-club-moderne", "neighborhood": "Lower Nob Hill/Polk", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('linden-room', 'Linden Room', 'San Francisco', 'CA', 'US', 37.779836, -122.420979, 'seed:mvp', '{"seed_id": "venue-linden-room", "neighborhood": "Hayes Valley", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('absinthe-brasserie-bar', 'Absinthe Brasserie Bar', 'San Francisco', 'CA', 'US', 37.783662, -122.431328, 'seed:mvp', '{"seed_id": "venue-absinthe-brasserie-bar", "neighborhood": "Hayes Valley", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('anina', 'Anina', 'San Francisco', 'CA', 'US', 37.774939, -122.426993, 'seed:mvp', '{"seed_id": "venue-anina", "neighborhood": "Hayes Valley", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('hazie-s', 'Hazie’s', 'San Francisco', 'CA', 'US', 37.781825, -122.428624, 'seed:mvp', '{"seed_id": "venue-hazie-s", "neighborhood": "Hayes Valley", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('sugar-lounge', 'Sugar Lounge', 'San Francisco', 'CA', 'US', 37.771753, -122.425025, 'seed:mvp', '{"seed_id": "venue-sugar-lounge", "neighborhood": "Hayes Valley", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('smuggler-s-cove', 'Smuggler''s Cove', 'San Francisco', 'CA', 'US', 37.775228, -122.428086, 'seed:mvp', '{"seed_id": "venue-smuggler-s-cove", "neighborhood": "Hayes Valley", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('phonobar', 'Phonobar', 'San Francisco', 'CA', 'US', 37.772647, -122.416481, 'seed:mvp', '{"seed_id": "venue-phonobar", "neighborhood": "Hayes Valley", "category": "live_music", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('brass-tacks', 'Brass Tacks', 'San Francisco', 'CA', 'US', 37.775547, -122.417596, 'seed:mvp', '{"seed_id": "venue-brass-tacks", "neighborhood": "Hayes Valley", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('fig-thistle', 'Fig & Thistle', 'San Francisco', 'CA', 'US', 37.777155, -122.432189, 'seed:mvp', '{"seed_id": "venue-fig-thistle", "neighborhood": "Hayes Valley", "category": "bar", "seed_version": "mvp_sf_2026_03"}'::jsonb),
  ('rich-table-bar', 'Rich Table Bar', 'San Francisco', 'CA', 'US', 37.783889, -122.418052, 'seed:mvp', '{"seed_id": "venue-rich-table-bar", "neighborhood": "Hayes Valley", "category": "lounge", "seed_version": "mvp_sf_2026_03"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  country_code = EXCLUDED.country_code,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  source = EXCLUDED.source,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
